### ISSUE TITLE
Obsolete?

### ISSUE THREAD

**Issue by danielbayley** [coffeelint/coffeelint#35]
@UziTech I just found [helixbass/eslint-plugin-coffee](https://github.com/helixbass/eslint-plugin-coffee#migrating-from-coffeelint)… So now wondering how this project fits into the CoffeeScript ecosystem? We don't want what remains of the CoffeeScript community to be duplicating effort…

**Comment by UziTech** [comment]
It's always good to have competition. That project does the same thing a different way (linting CoffeeScript). I wouldn't be hurt if everyone moved over to that plugin but until then I will continue to support coffeelint for any user that wants to use it.

**Comment by UziTech** [comment]
I actually moved away from using CoffeeScript in my projects a while ago. I just don't believe it is right to abandon a project that still has so many users.

**Comment by danielbayley** [comment]
Well I'll still support my PRs at least until they are merged…
