### ISSUE TITLE
Creating a v1.x branch

### ISSUE THREAD

**Issue by jacksonrayhamilton** [coffeelint/coffeelint#36]
I’d like to submit a PR to a branch which represents backports to the v1.x line for this project.  After that is merged we can publish another v1.x version.

Looking back on the repo’s history (https://github.com/clutchski/coffeelint/commits/master) I see that the last commit before the effort to upgrade to CS2 was [the 1.6.1 release](https://github.com/coffeelint/coffeelint/commit/f30dc439773a3f8a9b221583112b3c9f6d1e397e).  All commits after that were from https://github.com/clutchski/coffeelint/pull/596.  Strangely, there was no 1.6.1 published on NPM, only a 1.6.2, which is not Git-tagged.  I diffed the directories, and the only differences between the Git-tagged 1.6.1 and the NPM-published 1.6.2 that I could find were that the changes from https://github.com/clutchski/coffeelint/pull/602 were present in 1.6.1 and absent in 1.6.2.  Weird… possibly 1.6.2 was an attempt to revert https://github.com/clutchski/coffeelint/pull/602… but the PR looks like an enhancement, so maybe the difference was just a publishing goof.

All that examined, I say we start the `v1.x` branch at f30dc43 and let the next release be `v1.6.3` to avoid any ambiguity between the old and new NPM packages.

If you are comfortable with giving me branch creation permission so that I can do this myself, please do.  Despite being a member, I get this error when attempting that:

> git push -v coffeelint v1.x\:refs/heads/v1.x
> Pushing to git@github.com:coffeelint/coffeelint.git
> ERROR: Permission to coffeelint/coffeelint.git denied to jacksonrayhamilton.
> fatal: Could not read from remote repository.
> Please make sure you have the correct access rights
and the repository exists.

Also, in case I don’t have npm publishing permissions yet, those would also make me more autonomous as a member here.  Thanks!

**Comment by UziTech** [comment]
You should have write permissions now. and you do have publish permissions for @coffeelint/cli.

I created the [1.x](https://github.com/coffeelint/coffeelint/tree/1.x) branch at commit f30dc439773a3f8a9b221583112b3c9f6d1e397e

**Comment by jacksonrayhamilton** [comment]
Thanks, I finally got around to using this branch today.
