### ISSUE TITLE
Sorry

### ISSUE THREAD

**Issue by jacksonrayhamilton** [coffeelint/coffeelint#44]
I went ahead and published 1.6.3 with the “context” printing fix.

Unfortunately, this caused NPM to use the old README at https://www.npmjs.com/package/@coffeelint/cli.  I suppose it’ll switch back to the new one the next time a 3.x branch release goes out.

**Comment by UziTech** [comment]
that is because you released v1.6.3 to the latest tag. I'll look into how to switch it back

**Comment by UziTech** [comment]
I unpublished 1.6.3 and added 1.6.4 to the `@coffeelint/cli@old` tag

**Comment by UziTech** [comment]
Whenever you publish a new version from the 1.x branch you should use `npm publish --tag old`

**Comment by jacksonrayhamilton** [comment]
Ah, I see.  Thanks for the explanation.
